eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

server:
  port: 8903

spring:
  application:
    name: mobile-banking-service
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  show-actuator: true