eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

server:
  port: 8903

spring:
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    deserialization:
      fail-on-unknown-properties: true
